"""
Export RoleForge roles as opencode subagent markdown files.

Reads the free roles from the repo (roleforge/roles/) plus the paid catalog from the
local (non-repo) dir, validates every role, and writes one opencode agent file
(~/.config/opencode/agent/<role_id>.md) per role.

Usage:
    uv run python tools/export_opencode_agents.py
    uv run python tools/export_opencode_agents.py --dry-run
    uv run python tools/export_opencode_agents.py --role lead_internal_auditor
    uv run python tools/export_opencode_agents.py --free-only

Notes:
    - The paid catalog defaults to ~/.config/opencode/roleforge/roles/ (see
      tools/restore_paid_roles.py for how it is recovered).
    - Re-run after adding/editing roles to keep the opencode agents in sync.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

import yaml
from models import RoleDefinition
from loader import RoleLoader, RoleRegistry
from validators import RoleValidator

DEFAULT_PAID_DIR = Path.home() / ".config" / "opencode" / "roleforge" / "roles"
DEFAULT_OUTPUT_DIR = Path.home() / ".config" / "opencode" / "agent"


def first_sentence(text: str) -> str:
    """Return the first sentence of a description."""
    match = re.split(r"\.(?:\s|$)", text.strip())
    sentence = (match[0] if match else text.strip()).strip()
    if not sentence.endswith("."):
        sentence += "."
    return sentence


def build_description(role: RoleDefinition) -> str:
    """Concise, keyword-first description for the opencode agent frontmatter."""
    category = role.category.replace("_", " ")
    return f"{role.name} ({category}) — {first_sentence(role.description)}"


def build_prompt(role: RoleDefinition) -> str:
    """Portable persona prompt, mirroring the framework adapters' system prompt."""
    lines = [f"You are a {role.name}.", "", role.description.strip(), ""]
    lines.append("Your responsibilities:")
    for resp in role.responsibilities:
        lines.append(f"- {resp}")
    lines.append("")
    lines.append("Your areas of expertise:")
    for exp in role.expertise:
        lines.append(f"- {exp}")
    if role.recommended_tools:
        lines.append("")
        lines.append("Recommended tools:")
        for tool in role.recommended_tools:
            lines.append(f"- {tool}")
    lines.append("")
    lines.append(
        "When invoked as a subagent, focus on the task delegated to you, apply the "
        "expertise above, and return a clear, actionable result."
    )
    return "\n".join(lines)


def render_agent_file(role: RoleDefinition) -> str:
    """Render an opencode agent markdown file for a role."""
    frontmatter = {
        "description": build_description(role),
        "mode": "subagent",
    }
    header = yaml.safe_dump(
        frontmatter,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=1000,
    ).rstrip()
    body = build_prompt(role)
    return (
        "---\n"
        f"# Generated by roleforge tools/export_opencode_agents.py\n"
        f"{header}\n"
        "---\n\n"
        f"{body}\n"
    )


def load_merged_roles(free_only: bool, paid_dir: Path) -> list[RoleDefinition]:
    """Load repo (free) + paid roles, repo taking precedence on id collision."""
    merged: dict[str, RoleDefinition] = {}
    for role in RoleLoader(roles_dir=ROOT / "roles").load_all():
        merged[role.id] = role
    if not free_only:
        for role in RoleLoader(roles_dir=paid_dir).load_all():
            merged.setdefault(role.id, role)
    return list(merged.values())


def main() -> None:
    parser = argparse.ArgumentParser(description="Export RoleForge roles as opencode agents.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Where to write agent .md files")
    parser.add_argument("--paid-dir", type=Path, default=DEFAULT_PAID_DIR, help="Paid role catalog dir")
    parser.add_argument("--role", action="append", default=[], help="Only export this role id (repeatable)")
    parser.add_argument("--free-only", action="store_true", help="Only export the free starter roles")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written without writing")
    parser.add_argument("--force", action="store_true", help="Export even if validation errors are found")
    args = parser.parse_args()

    roles = load_merged_roles(args.free_only, args.paid_dir)
    if args.role:
        wanted = set(args.role)
        roles = [r for r in roles if r.id in wanted]

    roles.sort(key=lambda r: r.id)

    errors = RoleValidator(roles).validate_registry()
    if errors:
        print(f"Validation errors ({len(errors)}):")
        for e in errors:
            print(f"  - {e}")
        if not args.force:
            print("Aborting. Re-run with --force to export anyway.")
            sys.exit(1)

    out_dir = args.output_dir.resolve()
    written = 0
    for role in roles:
        filename = f"{role.id}.md"
        if args.dry_run:
            print(f"[dry-run] would write {out_dir / filename}")
            written += 1
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / filename).write_text(render_agent_file(role), encoding="utf-8")
        written += 1

    print(f"Source roles:        {len(roles)}")
    print(f"Output dir:          {out_dir}")
    print(f"Exported:            {written} agent file(s) ({'dry-run' if args.dry_run else 'written'})")


if __name__ == "__main__":
    main()
